package com.roottrace.ai.diagnosis;

import com.roottrace.incident.Incident;
import org.springframework.stereotype.Component;

/**
 * Builds the complete prompt for the AI diagnosis engine, including
 * system instructions, incident details, and retrieved context.
 */
@Component
public class DiagnosisPromptBuilder {

    /**
     * Builds the prompt string.
     *
     * @param incident   the incident being investigated
     * @param context    the bounded context string from retrieved knowledge
     * @param formatInstructions the JSON schema instructions generated by BeanOutputConverter
     * @return the complete prompt string
     */
    public String buildPrompt(Incident incident, String context, String formatInstructions) {
        return """
                SYSTEM INSTRUCTIONS:
                You are an expert site reliability engineer (SRE) and AI incident diagnosis engine.
                Your task is to analyze the provided incident details and the retrieved context from our knowledge base to determine the probable root cause and recommend actions.

                CRITICAL RULES:
                1. DO NOT invent causes, evidence, or citations that are not present in the provided context.
                2. If the provided context is insufficient to determine a root cause, you MUST state this clearly and assign a low confidence score (< 0.4).
                3. Every evidence item you provide MUST cite a specific Chunk ID from the retrieved context.
                4. Do not include sensitive information such as API keys or passwords.
                5. Provide concrete, actionable recommendations based on the evidence.

                INCIDENT DETAILS:
                Title: %s
                Service: %s
                Environment: %s
                Severity: %s
                Description:
                %s

                RETRIEVED EVIDENCE CONTEXT:
                %s

                FORMAT INSTRUCTIONS:
                %s
                """.formatted(
                incident.getTitle(),
                incident.getService(),
                incident.getEnvironment() != null ? incident.getEnvironment() : "N/A",
                incident.getSeverity(),
                incident.getDescription(),
                context,
                formatInstructions
        );
    }
}
