package com.roottrace.common.audit;

public enum AuditEventType {
    INCIDENT_CREATED,
    INCIDENT_UPDATED,
    INCIDENT_RESOLVED,
    INCIDENT_CLOSED,
    INCIDENT_DELETED,
    KNOWLEDGE_DOCUMENT_CREATED,
    KNOWLEDGE_DOCUMENT_READY,
    KNOWLEDGE_DOCUMENT_FAILED,
    KNOWLEDGE_DOCUMENT_DELETED,
    AI_DIAGNOSIS_CREATED,
    AI_DIAGNOSIS_FEEDBACK_SUBMITTED,
    AI_SIMILAR_INCIDENT_SEARCHED,
    INVESTIGATION_PLAN_CREATED,
    INVESTIGATION_STEP_UPDATED,
    INVESTIGATION_STEP_COMPLETED,
    POSTMORTEM_GENERATED,
    POSTMORTEM_UPDATED,
    POSTMORTEM_PUBLISHED,
    POSTMORTEM_ACTION_ITEM_CREATED,
    POSTMORTEM_ACTION_ITEM_UPDATED
}
